version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-id-12345
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    
  qdrant:
    image: qdrant/qdrant
    container_name: vectordb_dev
    restart: unless-stopped

    # REST on 6333, gRPC on 6334
    ports:
      - "6333:6333"
      - "6334:6334"

    # Optional tweaks and secrets go here
    #environment:
      # example: speed up background optimizers
      # - QDRANT__STORAGE__OPTIMIZER_THREADS=4
      # example: set an API key (uncomment to use)
      # - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

    # Persist collections, snapshots and WAL files
    volumes:
      - qdrant_data:/qdrant/storage


volumes:
  kafka_data:
  qdrant_data: